# Generated by Django 4.2 on 2023-05-21 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0004_remove_profile_about_me_profile_borndate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('Mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mentor', to='profileapp.profile', verbose_name='Первый воспитатель')),
                ('SecondMentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondMentor', to='profileapp.profile', verbose_name='Второй воспитатель')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('FirstName', models.CharField(max_length=200, verbose_name='Имя')),
                ('MiddleName', models.CharField(max_length=200, verbose_name='Отчество')),
                ('BornDate', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.childrengroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Дети',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
