# Generated by Django 4.2 on 2023-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrengroup',
            name='Age',
            field=models.CharField(default='', max_length=200, verbose_name='Возраст'),
        ),
    ]
