# Generated by Django 4.2 on 2023-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_childrengroup_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Название')),
                ('Age', models.CharField(max_length=200, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраст',
            },
        ),
        migrations.RenameField(
            model_name='childrengroup',
            old_name='Age',
            new_name='GroupAge',
        ),
    ]
