# Generated by Django 4.2 on 2023-05-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_groupage_rename_age_childrengroup_groupage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrengroup',
            name='GroupAge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.groupage', verbose_name='Возраст'),
        ),
    ]
