# Generated by Django 4.2 on 2023-05-21 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200, verbose_name='Класс')),
                ('SubClass', models.CharField(max_length=200, verbose_name='Подкласс')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2023, 5, 21), null=True, verbose_name='Дата')),
                ('Theme', models.CharField(max_length=200, null=True, verbose_name='Тема')),
                ('Task', models.TextField(null=True, verbose_name='Задачи')),
                ('Material', models.TextField(null=True, verbose_name='Организация предметно – пространственной развивающей среды')),
                ('Literature', models.TextField(null=True, verbose_name='Используемая литература')),
                ('Activities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.cactivities', verbose_name='Виды деятельности и культурные практики')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.childrengroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятие',
                'ordering': ('Date', 'Activities'),
            },
        ),
    ]
