# Generated by Django 4.2 on 2023-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lesson_date_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Year',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Год'),
        ),
    ]
