# Generated by Django 4.2 on 2023-05-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_children_group'),
        ('schedule', '0005_survey_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.TextField(null=True, verbose_name='Описание')),
                ('Survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.survey', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункт',
            },
        ),
        migrations.CreateModel(
            name='ChildrenScopeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.IntegerField(verbose_name='Оценка')),
                ('Children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.children', verbose_name='Группа')),
                ('Scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.survey', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результат',
            },
        ),
    ]
