# Generated by Django 4.2 on 2023-05-22 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_children_group'),
        ('schedule', '0006_scope_childrenscoperesult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='Survey',
        ),
        migrations.AddField(
            model_name='childrenscoperesult',
            name='Survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.survey', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='childrenscoperesult',
            name='Children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.children', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='childrenscoperesult',
            name='Scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.scope', verbose_name='Критерий'),
        ),
    ]
