# Generated by Django 4.2 on 2023-05-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_scope_survey_childrenscoperesult_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='Survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.survey', verbose_name='Тест'),
        ),
    ]
