# Generated by Django 4.2 on 2023-05-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_scope_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrenscoperesult',
            options={'ordering': ('Survey', 'Children', 'Survey'), 'verbose_name': 'Результат', 'verbose_name_plural': 'Результат'},
        ),
    ]
