# Generated by Django 4.2 on 2023-05-26 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_childrenscoperesult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 26), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Activities',
            field=models.CharField(choices=[('Социально-комуникативное развитие', 'Социально-комуникативное развитие'), ('Познавательное развитие', 'Познавательное развитие'), ('Речевое развитие', 'Речевое развитие'), ('Художественно-эстетическое развитие', 'Художественно-эстетическое развитие'), ('Физическое развитие', 'Физическое развитие')], default='Социально-комуникативное развитие', max_length=50, verbose_name='Вид развития'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Season',
            field=models.CharField(choices=[('Сентябрь', 'Сентябрь'), ('Май', 'Май')], default='Сентябрь', max_length=9, verbose_name='Месяц'),
        ),
    ]
