# Generated by Django 4.2 on 2023-05-31 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_lesson_date_alter_survey_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Score',
            field=models.IntegerField(max_length=1, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 31), null=True, verbose_name='Дата'),
        ),
    ]
