# Generated by Django 4.2 on 2023-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_lesson_score_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Score',
            field=models.IntegerField(default=0, max_length=1, null=True, verbose_name='Оценка'),
        ),
    ]
