# Generated by Django 4.2 on 2023-04-29 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_remove_profile_bio_profile_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.AddField(
            model_name='profile',
            name='BornDate',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='FirstName',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastName',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='MiddleName',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
